#!/bin/bash
#
#    01-header - display hostname, date and time, and kernel information
#
#    Authors: Chase Roohms <chaseroohms@gmail.com>

black='\e[0;30m'
blue='\e[0;34m'
green='\e[0;32m'
cyan='\e[0;36m'
red='\e[0;31m'
purple='\e[0;35m'
brown='\e[0;33m'
lightgray='\e[0;37m'
darkgray='\e[1;30m'
lightblue='\e[38;5;27m'
lightgreen='\e[1;32m'
lightcyan='\e[1;36m'
lightred='\e[1;31m'
lightpurple='\e[1;35m'
yellow='\e[1;33m'
white='\e[1;37m'
nc='\e[0m'


echo -ne "${white}${lightblue}"
toilet -f future -t "$HOSTNAME";
echo
echo -e "${lightblue}Today is:                 ${white}" `date "+%A %B %d, %Y"`
echo -e "${lightblue}Kernel Information:       ${white}" `uname -smr`
echo -e "${white}"
