#!/bin/bash
#
#    10-services - Displays information about the active services on this
#    machine
#
#    Authors: Chase Roohms <chaseroohms@gmail.com>

black='\e[0;30m'
blue='\e[0;34m'
green='\e[0;32m'
cyan='\e[0;36m'
red='\e[0;31m'
purple='\e[0;35m'
brown='\e[0;33m'
lightgray='\e[0;37m'
darkgray='\e[1;30m'
lightblue='\e[38;5;27m'
lightgreen='\e[1;32m'
lightcyan='\e[1;36m'
lightred='\e[1;31m'
lightpurple='\e[1;35m'
yellow='\e[1;33m'
white='\e[1;37m'
nc='\e[0m'

declare -A docker
#           docker[containername]="Name:                Description"

declare -A services
#           services[servicename]="Name:                Description"

declare -A apps
#               apps[prcoessname]="Name:                Description"

dockerinfo ()
{
  if [ ! ${#docker[@]} -eq 0 ]; then
    echo -e "${lightblue}Docker Services:"
    for key in "${!docker[@]}"
    do
      if [ "$(docker ps | grep $key)" ]; then
        echo -ne "    ${lightgreen}● "
      else
        echo -ne "    ${lightred}● "
      fi
      echo -e "${white}${docker[$key]}"
    done
  echo
  fi
}

serviceinfo ()
{
  if [ ! ${#services[@]} -eq 0 ] || [ ! ${#apps[@]} -eq 0 ]; then
    echo -e "${lightblue}Standalone Services:"
    for key in "${!services[@]}"
    do
      echo -ne "${lightred}"
      systemctl is-active --quiet $key && echo -ne "${lightgreen}"
      echo -ne "    ● "
      echo -e "${white}${services[$key]}"
    done
    for key in "${!apps[@]}"
    do
      if [ $(pidof -s $key) ]; then
        echo -ne "${lightgreen}    ● "
      else
        echo -ne "${lightred}    ● "
      fi
      echo -e "${white}${apps[$key]}"
    done
  echo
  fi
}

dockerinfo
serviceinfo
