#!/bin/bash
#
#    15-recentlogins - shows the last 3 logins on this machine (not including
#    the current)
#
#    Authors: Chase Roohms <chaseroohms@gmail.com>

black='\e[0;30m'
blue='\e[0;34m'
green='\e[0;32m'
cyan='\e[0;36m'
red='\e[0;31m'
purple='\e[0;35m'
brown='\e[0;33m'
lightgray='\e[0;37m'
darkgray='\e[1;30m'
lightblue='\e[38;5;27m'
lightgreen='\e[1;32m'
lightcyan='\e[1;36m'
lightred='\e[1;31m'
lightpurple='\e[1;35m'
yellow='\e[1;33m'
white='\e[1;37m'
nc='\e[0m'

recentlogins ()
{
  echo -e "${lightblue}Most Recent Logins:"

  for i in {4..2}
  do
    second=$(last | sed -n ${i}p | awk '{print $2}')
    if [ "$second" == ":1" ]; then
          echo -ne "    ${lightred}";last | sed -n ${i}p | awk '{print "terminal as " $1 " on " $4,$5,$6 " at " $7}'
    elif [[ "$second" == "pts/"* ]]; then
          echo -ne "    ${lightred}";last | sed -n ${i}p | awk '{print $3 " as " $1 " on " $4,$5,$6 " at " $7}'
    elif [ "$second" == "system" ]; then
          echo -ne "    ${lightred}";last | sed -n ${i}p | awk '{print $3 " as " $1 " on " $5,$6,$7 " at " $8}'
    else
          echo -ne "    ${lightred}";last | sed -n ${i}p
    fi
  done
}

#    End all update-motd with a newline
recentlogins
echo -e "${white}"
